import assert from 'node:assert/strict';
import { existsSync } from 'node:fs';
const moduleRoot = existsSync(new URL('./dist/planner.mjs',import.meta.url)) ? './dist/' : './';
const { makePlan, makeSession, estimateTimeline, validateProfile } = await import(moduleRoot+'planner.mjs');
const { mealOptions, assessMeal } = await import(moduleRoot+'meal.mjs');
const { packState, unpackState } = await import(moduleRoot+'storage.mjs');

const base={age:30,height:170,weight:75,targetWeight:70,days:3,minutes:30,budget:0,modes:['bodyweight','running'],goal:'loss',experience:'new',walking:'comfortable',pushups:'unknown',risk:false,diet:'mixed',exclusions:[]};
const start=new Date('2026-09-28T12:00:00');
let scenarios=0;
const modeKeys=['gym','bodyweight','pilates','running','hiking'];
for (const age of [30,65,80]) for (const experience of ['new','regular']) for (const days of [1,2,3,4,5,6,7]) for (const minutes of [10,15,30,45,180]) for (let mask=1;mask<32;mask++) {
  const modes=modeKeys.filter((_,i)=>mask&(1<<i));
  const p=makePlan({...base,age,balance:'clear',experience,days,minutes,modes,goal:mask%2?'muscle':'habit',hasGym:true},start);
  assert.equal(p.status,'ok');
  assert.equal(p.sessions.length,days);
  assert.equal(p.total,p.sessions.reduce((n,s)=>n+s.minutes,0));
  const loading=p.sessions.filter(s=>['strength','mat'].includes(s.type));
  for (const a of loading) for (const b of loading) if(a!==b) assert.ok(Math.min(Math.abs(a.day-b.day),7-Math.abs(a.day-b.day))>1,'recovery must separate loading days, including week boundary');
  for (const s of p.sessions) {
    assert.ok(s.minutes<=minutes && s.minutes<=45,'available time is a ceiling');
    assert.equal(s.blocks.reduce((n,b)=>n+b.minutes,0),s.minutes,'shown blocks fit the session');
    assert.ok(s.blocks.every(b=>b.minutes>0));
    assert.ok(s.strengthSets*2<=s.minutes-4,'sets include time for rest');
    assert.equal(s.balanceMinutes,age>=65?2:0);
    const brief=makeSession(s.mode,p.p,s.day,true);
    assert.equal(brief.minutes,10);
    assert.equal(brief.blocks.reduce((n,b)=>n+b.minutes,0),10);
    assert.equal(brief.balanceMinutes,age>=65?2:0);
  }
  scenarios++;
}

assert.equal(makePlan({...base,budget:''}).status,'error');
assert.equal(makePlan({...base,age:''}).field,'age');
assert.equal(makePlan({...base,modes:[]}).field,'modes');
assert.equal(makePlan({...base,days:1.5}).status,'error');
assert.equal(makePlan({...base,fat:70,muscle:60}).status,'error');
assert.equal(makePlan({...base,targetFat:70,targetMuscle:60}).status,'error');
assert.equal(makePlan({...base,risk:true}).status,'caution');
assert.equal(makePlan({...base,targetWeight:45}).status,'caution');
assert.equal(makePlan({...base,age:65}).status,'caution');
assert.equal(makePlan({...base,age:65,balance:'clear'}).status,'ok');
assert.equal(makePlan({...base,age:65,balance:'concern'}).status,'caution');
assert.equal(makePlan({...base,age:65,balance:'clear',walking:'hard'}).status,'caution');
assert.equal(makePlan({...base,age:65,balance:'clear',walking:'unknown'}).status,'caution');
assert.equal(makePlan({...base,age:17}).status,'error');
assert.equal(makePlan({...base,balance:'__proto__'}).status,'error');
for(const age of [18,29,40,55,64]) assert.deepEqual(makePlan({...base,age},start).sessions,makePlan(base,start).sessions,'do not fabricate age-based exercise multipliers');
assert.notDeepEqual(makePlan({...base,age:65,balance:'clear'},start).sessions,makePlan({...base,age:64},start).sessions);
for(const mode of ['bodyweight','gym','pilates']) for(const pushups of ['unknown','none','few','some','many']){
  const p=makePlan({...base,age:69,balance:'clear',modes:[mode],hasGym:true,avoidFloor:true,pushups},start);
  assert.equal(p.status,'ok');
  assert.ok(p.sessions.every(s=>s.moves.every(m=>!['bridge','bird','deadbug','side','floor'].includes(m.key))));
}
const scarce=makePlan({...base,age:65,balance:'clear',days:1,minutes:10},start);
assert.equal(scarce.sessions.length,1);
assert.equal(scarce.total,10);
assert.ok(scarce.reasons.some(r=>r.includes('3日')||r.includes('3일')));
assert.equal(makePlan({...base,targetFat:10}).status,'caution');
assert.equal(makePlan({...base,targetWeight:76}).status,'error');
assert.equal(makePlan({...base,targetWeight:'',fat:'',muscle:'',targetFat:'',targetMuscle:''}).status,'ok');
assert.equal(validateProfile({...base,modes:['__proto__','constructor']}).status,'error');
const poor=makePlan({...base,modes:['gym','running']});
assert.ok(poor.modes.includes('bodyweight') && poor.modes.includes('running'));
assert.ok(poor.sessions.some(s=>s.mode==='bodyweight'));
assert.ok(makePlan({...base,modes:['gym'],hasGym:true}).modes.includes('gym'));
assert.ok(makePlan({...base,modes:['gym'],budget:3,facilityCost:5}).modes.includes('bodyweight'));
assert.ok(makePlan({...base,modes:['gym'],budget:3,facilityCost:3}).modes.includes('gym'));
assert.ok(makePlan({...base,modes:['pilates']}).modes.includes('pilates'),'mat Pilates is available without a facility');
const simple=makePlan({...base,modes:['running'],goal:'habit',targetWeight:null});
const muscle=makePlan({...base,modes:['running'],goal:'habit',targetWeight:null,muscle:28,targetMuscle:29});
assert.ok(!simple.sessions.some(s=>s.type==='strength'));
assert.ok(muscle.sessions.some(s=>s.type==='strength'),'muscle goal changes actual plan');
assert.equal(makeSession('gym',{...base,minutes:10,pushups:'some'}).moves.find(m=>m.key==='incline').reps,'편안하게 4~6회');
assert.ok(!makeSession('running',{...base,walking:'unknown'}).blocks.some(b=>b.detail.includes('달리기 1분')));
assert.ok(!makeSession('running',base,1).blocks.some(b=>b.detail.includes('달리기 1분')),'beginner run intervals are not daily');
assert.ok(!makePlan(base).timeline.match(/\d+~\d+주/),'no fabricated arrival forecast');
assert.match(estimateTimeline({earlier:76,recent:75,weeks:4,target:70,height:170}).title,/20주/);
assert.equal(estimateTimeline({earlier:75,recent:75,weeks:4,target:70}).status,'caution');
assert.equal(estimateTimeline({earlier:74,recent:75,weeks:4,target:70}).status,'caution');
assert.equal(estimateTimeline({earlier:85,recent:75,weeks:2,target:70}).status,'caution');
assert.equal(estimateTimeline({earlier:76,recent:75,weeks:0,target:70}).status,'error');
assert.equal(estimateTimeline({earlier:55,recent:53,weeks:4,target:50,height:170}).status,'caution');
assert.equal(mealOptions({...base,diet:'plant',exclusions:['soy','legume']}).protein,null);
for (let i=0;i<6;i++) assert.ok(!['달걀','생선','닭고기'].includes(mealOptions({...base,diet:'plant'},'store',i).protein));
assert.ok(!mealOptions({...base,goal:'habit',targetWeight:''}).focus.includes('간식'));
assert.match(assessMeal({vegetable:true,protein:true,grain:true,amount:'more'}).actions[0],/굶거나 추가 운동/);
const now=Date.parse('2026-09-28T00:00:00Z');
const packed=packState({...base,photo:'secret-bytes'},new Set(['2026-09-28']),'2026-09-28',now,new Set(['2026-09-28']));
assert.ok(!packed.includes('secret-bytes'),'photo data is never persisted');
assert.deepEqual(unpackState(packed,now).shortened,['2026-09-28']);
assert.equal(unpackState(packed,now+31*86400000),null);
assert.equal(unpackState('{bad json}',now),null);
assert.equal(unpackState(JSON.stringify({version:2,expires:now+1000,profile:{age:30},startDate:'2026-09-28',completed:[]}),now),null);
console.log(`${scenarios}개 일정 조합: 시간 합계·회복일·축소 계획 통과. 입력·목표 반영·예산·식사 제한·기간·저장 검증 통과.`);
